[toolchain]
solana_version = "2.1.0"
anchor_version = "0.31.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_staking = "8y11v8SN4VfbasLdPAHBrnVXRQsuCXgFUBWyyC2Hd9LD"

[programs.devnet]
solana_staking = "8y11v8SN4VfbasLdPAHBrnVXRQsuCXgFUBWyyC2Hd9LD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[test]
startup_wait = 10000
